services:
  perpustakaan:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_URL=mysql://root:root@db:3306/dj_perpustakaan
    depends_on:
      db:
        condition: service_healthy
    networks:
      - library-network

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dj_perpustakaan
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - library-network

volumes:
  db_data:

networks:
  library-network:
    driver: bridge
