# Generated by Django 5.1.5 on 2025-01-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahun', models.IntegerField(max_length=4)),
                ('kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('no_telpon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('id_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buku')),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahasiswa')),
            ],
        ),
    ]
