# Generated by Django 5.1.5 on 2025-01-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='tahun',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='no_telpon',
            field=models.CharField(max_length=13),
        ),
    ]
